isv:
  registerMiniprogram: post:https://api.weixin.qq.com/cgi-bin/component/fastregisterweapp?action=create&component_access_token=TOKEN


#默认可覆盖
dows:
  ods:
    model:
      scanBasePackage: org.dows.ods.demo.model1
      classes:
        user: org.dows.ods.demo.model.User
        job: org.dows.ods.demo.model.Job
    biz:
      scanBasePackage: org.dows.ods.demo.biz
      classes:
        user: org.dows.ods.demo.model.UserBiz
        job: org.dows.ods.demo.model.JobBiz
    bizs:
      #      - clazz:  org.dows.ods.demo.ScriptExecuterService
      #        bizScripts:
      #          - enable: true
      #            name: uploadExpData
      #            cmd: policy:jdbc://initExp
      #            env: test

      - clazz: org.dows.ods.demo.ScriptExecuterService
        bizScripts:
          - enable: true
            name: initExp(Request)
            #cmd: userBiz*login(rt*ticket,env*appSecret,jobBiz*addJob(rt*user:class,env*appSecret)))
            cmd: zghydx:rest://openapi?$.[?(@.error empty)]:$.error&$.message:userExperimentsResponse.class->policy:local://initExp
            #cmd: hnilab:rest://checkToken?$.[?(@.success == true)]->hnilab:rest://getUserInfo?$.rows->gpm:calc://saveAccountToken?$.account #->findsoft:cache://saveAccountToken?$.account->hnilab:rest://getToken?$.rows.accesstoken
            #cmd: hnilab:rest://checkToken?$.[?(@.success == true)]->hnilab:rest://getUserInfo?$.rows->hep:local://saveAccountTokenAndUserInfo?$.account #->findsoft:cache://saveAccountToken?$.account->hnilab:rest://getToken?$.rows.accesstoken
            #cmd: njykdx:rest://getToken?$.[?(@.code != 0)]:$.msg&$.user.name:userName,$.pwd:pwd11->heropro:rest://regist
            #cmd: ods:rest://getJsonData?$.[?(@.code == 200)]:$.descr&$.data.age:age;$.data.['name','age']:user.class->ods:rest://postJsonData
            #cmd: ods:rest://getJsonData?$.[?(@.code == 200)]:$.descr&$.data:experimentDataUploadResponse.class->ods:rest://postJsonData
            #cmd: ods:rest://getJsonData?$.[?(@.code == 200)]:$.descr&$.data.age:age;$.data.user:user.class->heropro:jdbc://saveOdsDemo
            #cmd: ods:rest://getJsonData?$.[?(@.code == 200)]:$.descr&$.data.age:age;$.data.user:user.class && ods:rest://postJsonData
            env: test

          - enable: true
            name: completeExp
            #cmd: gpm:jdbc://getExperimentResult->hnilab:rest://saveOperateRecordData?$.[?(@.success == true)]
            cmd: policy:jdbc://getExperimentResult->policy:local://convertExperimentDataUpload->zghydx:rest://dataUpload?$.[?(@.success == true)]
            env: test

    #      - clazz: org.dows.ods.demo.DemoBiz1
    #        methods:
    #          - enable: true
    #            name: completeExp
    #            cmd: findsoft:jdbc://getExperimentResult->hnilab:rest://saveOperateRecordData
    #            env: test
    #          - enable: true
    #            name: completeEEE
    #            env: test
    # 通道名端点配置  bean*aa()
    endpoints:
      - endpointId: 0
        type: rest
        channel: zghydx
        enable: false
        apis:
          openapi: post:/openapi/${rt*appId}/sign=${md5(rt*ticket,env*appSecret,tmp*md5(rt*user.class,env*appSecret))}
          #openapi: post:/openapi/d90e8b9d-6be8-4d1f-981a-d3bd8b7d9cc0
          dataUpload: post:/openapi/data_upload
        envs:
          - name: test
            host: https://api.vr-mooc.com
            port:
            username:
            token:
            appId: 0fd41aec6bb7486aa86d0f276dda9ee774d790039b90481e98a1a0694d3db3dd
            appSecret: 0105BC30C5526E7B6B6446549EB0676DF4A668FA6F49AC11C9B81A905855527A080A65853074B5A51F219CA7320FFC7AA12108B08038AE0FD08041A916F8AEAFEB0CC36B765CCAC5
          - name: prd
            host: https://www.hnilab.com
            port:
            username:
            token:
            appId: 3dfe80096e234a3798d05d3f0bd6610e01a1e53b855a4e0b94c36edec31b5217
            appSecret: 6CE2715036F894F8F48BD85C1335D74D0083A36133C6282B26610E2DB7ED89A3A08F286AF4FF5E620CAE48B8CCD09B5B3657E364087C2F22285BEDDE00C8A95799C46201162E8808

      - endpointId: -1
        type: local
        channel: policy
        enable: true
        apis:
          initExp: local:/org.policy.ExperimentInit/initExp
          dataUpload: post:/openapi/data_upload
        envs:
          - name: test
            host: https://api.vr-mooc.com
            port:
            username:
            token:
            appId: 0fd41aec6bb7486aa86d0f276dda9ee774d790039b90481e98a1a0694d3db3dd
            appSecret: 0105BC30C5526E7B6B6446549EB0676DF4A668FA6F49AC11C9B81A905855527A080A65853074B5A51F219CA7320FFC7AA12108B08038AE0FD08041A916F8AEAFEB0CC36B765CCAC5
          - name: prd
            host: https://www.hnilab.com
            port:
            username:
            token:
            appId: 3dfe80096e234a3798d05d3f0bd6610e01a1e53b855a4e0b94c36edec31b5217
            appSecret: 6CE2715036F894F8F48BD85C1335D74D0083A36133C6282B26610E2DB7ED89A3A08F286AF4FF5E620CAE48B8CCD09B5B3657E364087C2F22285BEDDE00C8A95799C46201162E8808

      - endpointId: -1
        type: jdbc
        channel: policy
        enable: true
        apis:
          queryExpData: select:/org.policy.ExperimentInit/initExp
          saveUserInfo: insert:/insert into user() value(?,?)
        envs:
          - name: test
            host: https://api.vr-mooc.com
            port:
            username:
            token:
            appId: 0fd41aec6bb7486aa86d0f276dda9ee774d790039b90481e98a1a0694d3db3dd
            appSecret: 0105BC30C5526E7B6B6446549EB0676DF4A668FA6F49AC11C9B81A905855527A080A65853074B5A51F219CA7320FFC7AA12108B08038AE0FD08041A916F8AEAFEB0CC36B765CCAC5
          - name: prd
            host: https://www.hnilab.com
            port:
            username:
            token:
            appId: 3dfe80096e234a3798d05d3f0bd6610e01a1e53b855a4e0b94c36edec31b5217
            appSecret: 6CE2715036F894F8F48BD85C1335D74D0083A36133C6282B26610E2DB7ED89A3A08F286AF4FF5E620CAE48B8CCD09B5B3657E364087C2F22285BEDDE00C8A95799C46201162E8808


      - endpointId: 1
        type: rest
        channel: hnilab
        enable: false
        apis:
          checkToken: post:/api/OpenData/CheckToken
          getToken: post:/api/OpenData/GetToken
          getUserInfo: get:/api/OpenData/GetUserInfo
          saveOperateRecordData: post:/api/OpenData/SaveOperateRecordData
        envs:
          - name: test
            host: https://testapi.hnilab.com
            port:
            username:
            token:
            appId: 0fd41aec6bb7486aa86d0f276dda9ee774d790039b90481e98a1a0694d3db3dd
            appSecret: 0105BC30C5526E7B6B6446549EB0676DF4A668FA6F49AC11C9B81A905855527A080A65853074B5A51F219CA7320FFC7AA12108B08038AE0FD08041A916F8AEAFEB0CC36B765CCAC5
          - name: prd
            host: https://www.hnilab.com
            port:
            username:
            token:
            appId: 3dfe80096e234a3798d05d3f0bd6610e01a1e53b855a4e0b94c36edec31b5217
            appSecret: 6CE2715036F894F8F48BD85C1335D74D0083A36133C6282B26610E2DB7ED89A3A08F286AF4FF5E620CAE48B8CCD09B5B3657E364087C2F22285BEDDE00C8A95799C46201162E8808



      - endpointId: 2
        type: calc
        channel: gpm
        enable: false
        apis:
          saveAccountToken: calc:/org.dows.ods.client.OdsTokenContext/addThirdToken
        envs:
          - name: test
            host:
            port:
            username:
            token:
            appId:
            appSecret:
          - name: prd
            host:
            port:
            username:
            token:
            appId:
            appSecret:

      - endpointId: 3
        type: calc
        channel: heropro
        enable: false
        apis:
          getExperimentResult: calc:/org.dows.ods.client.OdsTokenContext/addThirdToken
        envs:
          - name: test
            host:
            port:
            username:
            token:
            appId:
            appSecret:
          - name: prd
            host:
            port:
            username:
            token:
            appId:
            appSecret:


      - endpointId: 4
        type: calc
        channel: common
        enable: false
        apis:
          ioConvert: calc:/org.dows.ods.client.ObjectConvert/convert
        envs:
          - name: test
            host: https://testapi.hnilab.com
            port:
            username:
            token:
            appId: 0fd41aec6bb7486aa86d0f276dda9ee774d790039b90481e98a1a0694d3db3dd
            appSecret: 0105BC30C5526E7B6B6446549EB0676DF4A668FA6F49AC11C9B81A905855527A080A65853074B5A51F219CA7320FFC7AA12108B08038AE0FD08041A916F8AEAFEB0CC36B765CCAC5
          - name: prd
            host: https://www.hnilab.com
            port:
            username:
            token:
            appId: 3dfe80096e234a3798d05d3f0bd6610e01a1e53b855a4e0b94c36edec31b5217
            appSecret: 6CE2715036F894F8F48BD85C1335D74D0083A36133C6282B26610E2DB7ED89A3A08F286AF4FF5E620CAE48B8CCD09B5B3657E364087C2F22285BEDDE00C8A95799C46201162E8808



      - endpointId: 5
        type: rest
        channel: heropro
        enable: false
        apis:
          regist: post:/v1/api/regist
        envs:
          - name: test
            host: https://hreopro.findsoft.com
            port:
            username:
            token:
            appId:
            appSecret:
          - name: prd
            host: https://www.hnilab.com
            port:
            username:
            token:
            appId: 3dfe80096e234a3798d05d3f0bd6610e01a1e53b855a4e0b94c36edec31b5217
            appSecret: 6CE2715036F894F8F48BD85C1335D74D0083A36133C6282B26610E2DB7ED89A3A08F286AF4FF5E620CAE48B8CCD09B5B3657E364087C2F22285BEDDE00C8A95799C46201162E8808




      - endpointId: 6
        type: rest
        channel: gpm
        enable: false
        #        apis:
        #          checkToken:
        #          getToken:
        #          getUserInfo:
        #          saveOperateRecordData:
        envs:
          - name: test
            host: http://gpm.findsoft.com
            port:
            username:
            token:
            appId:
            appSecret:
          - name: prd
            host: http://gpm.findsoft.com
            port:
            username:
            token:
            appId:
            appSecret:

      - endpointId: 7
        type: jdbc
        channel: gpm
        module:
        pkg:
        enable: false
        apis:
          getExperimentResult: select:/select account_name as projectName from account_instance where app_id=:appId and status=:status and userId=:userId
        envs:
          - name: test
            host: jdbc:mysql://192.168.1.60:3306/dows_uim?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
            port: 3306
            username: root
            token: root
          - name: prd
            host: jdbc:mysql://192.168.1.60:3306/dows_uim?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
            port: 3306
            username: root
            token: root

      - endpointId: 8
        type: jdbc
        channel: heropro
        module:
        pkg:
        enable: false
        apis:
          saveOdsDemo: insert:/insert into account_name('name',age) value(?,?)
          selectOdsDemo: select:/select * from account where name=? and age = ? and xxx
          getExperimentResult: select:/select account_name as projectName from account_instance where app_id=:appId and status=:status
        envs:
          - name: test
            host: jdbc:mysql://192.168.1.60:3306/dxz?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
            port: 3306
            username: root
            token: root
          - name: prd
            host: jdbc:mysql://192.168.1.60:3306/dows_uim?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
            port: 3306
            username: root
            token: root



      - endpointId: 9
        type: rest
        channel: njykdx
        enable: false
        apis:
          getToken: get:/api/v1/Token/Get?ticket=${rt*ticket}&signature=${md5(rt*ticket,env*appSecret)}
          refreshToken: get:/api/v1/Token/Refresh?access_token&signature
          getUserInfo: get:/api/v1/User/Validate?username&password&nonce&signature=MD5:secret_key,nonce,username
          uploadExperimentResult: post:/api/v1/Resource/UploadResult
        envs:
          - name: test
            host: http://114.217.30.222:81/njykdx_xnfz
            port:
            username:
            token:
            appId:
            appSecret: 516823eb8d8748f9b031ec5e91d5b49b
          - name: prd
            host:
            port:
            username:
            token:
            appId:
            appSecret:

      - endpointId: 10
        type: rest
        channel: ods
        enable: false
        apis:
          getJsonData: get:/getJsonData
          postJsonData: post:/postJsonData
        envs:
          - name: test
            host: http://127.0.0.1:9000
            port:
            username:
            token:
            appId:
            appSecret: 516823eb8d8748f9b031ec5e91d5b49b
          - name: prd
            host:
            port:
            username:
            token:
            appId:
            appSecret: