server:
  port: 9001
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
#  servlet:
#    context-path: /${spring.application.name}

log:
  binlog:
    hosts:
      - name: dxz
        host: sh-cdb-1qjrazc8.sql.tencentcdb.com
        port: 63915
        username: admin
        password: dxzsaas@!
        timeOffset: 1000
        filter:
          # 全部填 *，指定某个数据库所有表填写 db_name.*
          includes: dxz.*
          #  - dows.log_ddl_demo
          # 不做排除 填写空 "" ,excludes 规则优先级高于 includes
          excludes: ""
          #  - dows.log_ddl_demo
spring:
  application:
    name: dows-pay
  profiles:
    include: mysql,mybatis,mvc,redis,alipay,ssh
    active: sit
#debug: true
# 图片上传url
upload:
  path: ${user.dir}/uploads/store/table/
# 小程序点单页面URL
order:
  url: http://81.69.171.79:9011/order
# 微信配置
wx:
  miniapp:
    configs:
      #      - appid: wx30b441ca0d8beb3c #微信小程序的appid
      #        secret: 624b9a69f61e5abf7bd47b07f6134a8b #微信小程序的Secret
      - appid: wx910b869b1a2a2ab2 #微信小程序的appid
        secret: 40cad8214a4c74c9e2c7e9b30eeb6289 #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
ws:
  port: 9999