dows:
  sdk:
    weixin:
      "org.dows.sdk.weixin.open.openApi管理.OpenApi管理Api.重置API调用次数": POST https://api.weixin.qq.com/cgi-bin/clear_quota?access_token=ACCESS_TOKEN
      "org.dows.sdk.weixin.open.openApi管理.OpenApi管理Api.查询API调用额度": POST https://api.weixin.qq.com/cgi-bin/openapi/quota/get?access_token=ACCESS_TOKEN
      "org.dows.sdk.weixin.open.openApi管理.OpenApi管理Api.查询rid信息": POST https://api.weixin.qq.com/cgi-bin/openapi/rid/get?access_token=ACCESS_TOKEN
      "org.dows.sdk.weixin.open.openApi管理.OpenApi管理Api.使用AppSecret重置第三方平台 API 调用次数": POST https://api.weixin.qq.com/cgi-bin/component/clear_quota/v2
